backend:
  name: github
  repo: reguv760/gatsby-storeytime

media_folder: static/assets
public_folder: assets

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/videos/index.md'
        label: 'Video List'
        name: 'videoList'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'video-page',
            }
          - label: 'Videos'
            name: 'videos'
            widget: 'list'
            fields:
              - { label: 'Video Title', name: 'videoTitle', widget: 'string' }
              - {
                  label: 'Youtube Embed URL',
                  name: 'videoLink',
                  widget: 'string',
                }

      - file: 'src/pages/singers/index.md'
        label: 'Singer List'
        name: 'singerList'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'singer-page',
            }
          - label: 'Singer'
            name: singer
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'Body', name: 'body', widget: 'markdown' }

      - file: 'src/pages/events/index.md'
        label: 'Events'
        name: 'eventsList'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'event-page',
            }

          - label: 'Event'
            name: 'event'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'eventName', widget: 'string' }
              - { label: 'Status', name: 'eventStatus', widget: 'string' }
              - {
                  label: 'Event Date',
                  name: 'eventDate',
                  widget: 'date',
                  default: '',
                  format: 'MMM Do YY',
                }
              - {
                  label: 'Event Start time',
                  name: 'eventStartTime',
                  widget: 'datetime',
                  default: '',
                  format: 'hh:mm a',
                }
              - {
                  label: 'Event End time',
                  name: 'eventEndTime',
                  widget: 'datetime',
                  default: '',
                  format: 'hh:mm a',
                }
              - { label: 'Event Img', name: 'eventImage', widget: 'image' }
              - {
                  label: 'Event Fee',
                  name: 'eventFee',
                  widget: 'number',
                  default: '0',
                }
              - { label: 'Street', name: 'eventStreet', widget: 'string' }
              - { label: 'City', name: 'eventCity', widget: 'string' }
              - { label: 'State', name: 'eventState', widget: 'string' }
              - { label: 'Zip', name: 'eventZip', widget: 'string' }
              - {
                  label: 'Contact Name',
                  name: 'eventContactName',
                  widget: 'string',
                }
              - {
                  label: 'Contact Phone',
                  name: 'eventContactPhone',
                  widget: 'string',
                }
              - {
                  label: 'Contact Email',
                  name: 'eventContactEmail',
                  widget: 'string',
                }
              - { label: 'Event Desc', name: 'eventDesc', widget: 'string' }
              - {
                  label: 'Special Notes',
                  name: 'eventSpecialNotes',
                  widget: 'string',
                }
          - { label: 'Paypal ID', name: 'paypalID', widget: 'string' }

      - file: 'src/pages/donate/index.md'
        label: 'Donate'
        name: 'donate'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'donate-page',
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Paypal ID', name: 'paypalID', widget: 'string' }

  - name: 'layout'
    label: 'Page Layout'
    delete: false
    files:
      - file: 'src/pages/index.md'
        label: 'Company Info, Banner, HomeNav, Footer and Contact Components'
        name: 'home'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index',
            }
          - { label: 'Enable Banner', name: 'bannerEnabled', widget: 'boolean' }
          - { label: 'Title', name: 'bannerTitle', widget: 'string' }
          - { label: 'Text', name: 'bannerText', widget: 'markdown' }
          - { label: 'Slogan', name: 'bannerSlogan', widget: 'string' }

          - label: 'Home Nav Images'
            name: 'homeNavImages'
            widget: 'list'
            fields:
              - { label: 'Background Image', name: 'bgImage', widget: 'image' }
              - { label: 'Image Title', name: 'imageTitle', widget: 'string' }
              - { label: 'Image Text', name: 'imageText', widget: 'string' }
              - { label: 'Page Path', name: 'pagePath', widget: 'string' }

          - { label: 'Company Name', name: 'companyName', widget: 'string' }
          - { label: 'Company Logo', name: 'companyLogo', widget: 'image' }

          - label: 'Social Media Icons'
            name: 'socialIcons'
            widget: 'list'
            fields:
              - {
                  label: 'Enable Icon',
                  name: 'socialEnabled',
                  widget: 'boolean',
                }
              - { label: 'Link', name: 'socialLink', widget: 'string' }

          - { label: 'Designed By', name: 'designedBy', widget: 'string' }
          - { label: 'Design Link', name: 'designLink', widget: 'string' }

          - { label: 'Contact Phone', name: 'contactPhone', widget: 'string' }
          - { label: 'Contact Email', name: 'contactEmail', widget: 'string' }
          - {
              label: 'Contact Address',
              name: 'contactAddress',
              widget: 'markdown',
            }
